# Generated by Django 3.2.9 on 2021-12-31 17:13

import FreeLims.models
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_name', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=200)),
                ('sample_description', models.CharField(max_length=200)),
                ('tracking_number', models.CharField(max_length=100)),
                ('sample_volume', models.CharField(max_length=100)),
                ('sample_quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('sample_type', models.CharField(choices=[('Solid', 'Solid'), ('Liquid', 'Liquid'), ('Powder', 'Powder')], max_length=100)),
                ('expiration_date', models.DateTimeField(default=None, max_length=100, null=True)),
                ('logged_date', models.DateTimeField(default=datetime.datetime.now)),
                ('initiated', models.BooleanField(default=False)),
                ('sample_test', models.CharField(choices=[('Reverse Phase HPLC', 'Reverse Phase HPLC'), ('SEC HPLC', 'SEC HPLC'), ('UV-VIS', 'UV-VIS'), ('Moisture by Karl-Fischer', 'Moisture by Karl-Fischer'), ('pH', 'pH'), ('Dissolution', 'Dissolution'), ('Wet Chemistry', 'Wet Chemistry'), ('Raw Material', 'Raw Material'), ('CTL Testing', 'CTL Testing')], max_length=200, null=True)),
                ('initiated_date', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('report_date', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('result_pf', models.BooleanField(blank=True, choices=[(True, 'Pass'), (False, 'Fail')], default=None, max_length=4, null=True)),
                ('sample_result', models.CharField(default=None, max_length=100, null=True)),
                ('comments', models.CharField(default=None, max_length=200, null=True)),
                ('reference', models.CharField(default=None, max_length=200, null=True)),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiatedUser', to=settings.AUTH_USER_MODEL)),
                ('logged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportedUser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['expiration_date'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=100)),
                ('last_name', models.CharField(default=None, max_length=100)),
                ('empl_ID', models.CharField(default=None, max_length=100)),
                ('organization', models.CharField(default=None, max_length=125, null=True)),
                ('role', models.CharField(choices=[('Lab Technician', 'Lab Technician'), ('Manufacturing Technician', 'Manufacturing Technician'), ('Analyst', 'Analyst'), ('QC Analyst', 'QC Analyst'), ('Manufacturing Analyst', 'Manufacturing Analyst'), ('Lead Analyst', 'Lead Analyst'), ('Lead QC Analyst', 'Lead QC Analyst'), ('Lead Mfg Analyst', 'Lead Mfg Analyst'), ('Supervisor', 'Supervisor'), ('QC Supervisor', 'QC Supervisor'), ('Mfg Supervisor', 'Mfg Supervisor'), ('Manager', 'Manager'), ('Director', 'Director')], default=None, max_length=100, null=True)),
                ('department', models.CharField(choices=[('GENERAL LAB', 'GENERAL LAB'), ('QC CHEM', 'QC CHEM'), ('QC MICRO-BIO', 'QC MICRO-BIO'), ('QC BIO', 'QC BIO'), ('MANUFACTURING', 'MANUFACTURING')], default=None, max_length=100, null=True)),
                ('location', models.CharField(default=None, max_length=150, null=True)),
                ('Secret_Key', models.CharField(default=FreeLims.models.generateHiddenKey, max_length=100)),
                ('email', models.CharField(default=None, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cheminventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(default=None, max_length=125, null=True)),
                ('logged_date', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('name', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(choices=[('Fisher Scientific', 'Fisher Scientific'), ('ThermoFisher Scientific', 'ThermoFisher Scientific'), ('Acros Organic', 'Acros Organic'), ('Sigma-Aldrich', 'Sigma-Aldrich'), ('Agilent', 'Agilent'), ('MilliporeSigma', 'MilliporeSigma'), ('Mettler Toledo', 'Mettler Toledo')], max_length=100)),
                ('manufacturer_lot', models.CharField(max_length=100)),
                ('expiry', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('Lab_lot', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('volume_size', models.CharField(max_length=100)),
                ('location', models.CharField(choices=[('General Lab Storage', 'General Lab Storage (25°C)'), ('Refrigerator', 'Refrigerator (2-8°C)'), ('Freezer', 'Freezer')], max_length=100)),
                ('comments', models.CharField(max_length=250)),
                ('quarantine', models.BooleanField(default=False)),
                ('open_container', models.BooleanField(blank=True, choices=[(True, 'Open'), (False, 'Close')], default=True, null=True)),
                ('inv_disposal', models.BooleanField(blank=True, choices=[(True, 'Disposed'), (False, 'Active')], default=False, null=True)),
                ('disposal_date', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('disposal_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disposalUser', to=settings.AUTH_USER_MODEL)),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['expiry'],
            },
        ),
    ]
