# Generated by Django 3.2.9 on 2021-12-09 01:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=200)),
                ('sample_name', models.CharField(max_length=100)),
                ('sample_description', models.CharField(max_length=200)),
                ('tracking_number', models.CharField(max_length=100)),
                ('sample_volume', models.CharField(max_length=100)),
                ('sample_quantity', models.IntegerField()),
                ('sample_type', models.CharField(choices=[('Solid', 'Solid'), ('Liquid', 'Liquid'), ('Powder', 'Powder')], max_length=100)),
                ('expiration_date', models.CharField(max_length=100)),
                ('logged_date', models.DateTimeField()),
                ('initiated', models.BooleanField(default=False)),
                ('sample_test', models.CharField(choices=[('Reverse Phase HPLC', 'Reverse Phase HPLC'), ('SEC HPLC', 'SEC HPLC'), ('UV-VIS', 'UV-VIS'), ('Moisture by Karl-Fischer', 'Moisture by Karl-Fischer'), ('pH', 'pH'), ('Dissolution', 'Dissolution'), ('Wet Chemistry', 'Wet Chemistry'), ('Raw Material', 'Raw Material'), ('CTL Testing', 'CTL Testing')], max_length=200, null=True)),
                ('initiated_date', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('report_date', models.DateTimeField(null=True)),
                ('result_pf', models.BooleanField(blank=True, choices=[(True, 'Pass'), (False, 'Fail')], default=None, max_length=4, null=True)),
                ('sample_result', models.CharField(default=None, max_length=100, null=True)),
                ('comments', models.CharField(default=None, max_length=200, null=True)),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiatedUser', to=settings.AUTH_USER_MODEL)),
                ('logged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportedUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
