# Generated by Django 3.2.9 on 2021-11-19 01:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FreeLims', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=200)),
                ('sample_name', models.CharField(max_length=100)),
                ('sample_description', models.CharField(max_length=200)),
                ('tracking_number', models.CharField(max_length=100)),
                ('sample_volume', models.CharField(max_length=100)),
                ('sample_quantity', models.IntegerField()),
                ('sample_type', models.CharField(choices=[('Solid', 'Solid'), ('Liquid', 'Liquid'), ('Powder', 'Powder')], max_length=100)),
                ('expiration_date', models.CharField(max_length=100)),
                ('logged_date', models.DateTimeField(default=datetime.datetime.now)),
                ('logged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='profile',
        ),
    ]
