# Generated by Django 3.2.9 on 2021-11-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreeLims', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=200)),
                ('sample_name', models.CharField(max_length=100)),
                ('sample_description', models.CharField(max_length=200)),
                ('tracking_number', models.CharField(max_length=100)),
                ('sample_volume', models.CharField(max_length=100)),
                ('sample_quantity', models.CharField(max_length=100)),
                ('sample_type', models.CharField(choices=[('Solid', 'Solid'), ('Liquid', 'Liquid'), ('Powder', 'Powder')], max_length=100)),
                ('expiration_date', models.CharField(max_length=100)),
                ('logged_date', models.CharField(max_length=100)),
                ('logged_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='profile',
        ),
    ]
