# Generated by Django 3.2.9 on 2021-12-09 01:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreeLims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='logged_date',
            field=models.DateTimeField(verbose_name=datetime.datetime.now),
        ),
    ]
