# Generated by Django 3.2.9 on 2021-12-09 01:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreeLims', '0002_alter_sample_logged_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='logged_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='sample',
            name='report_date',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
