# Generated by Django 3.2.9 on 2022-01-14 21:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FreeLims', '0002_auto_20220105_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='review_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewerUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sample',
            name='review_date',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(choices=[('', 'Department'), ('GENERAL LAB', 'GENERAL LAB'), ('QC CHEM', 'QC CHEM'), ('QC MICRO-BIO', 'QC MICRO-BIO'), ('QC BIO', 'QC BIO'), ('MANUFACTURING', 'MANUFACTURING')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Lab Technician', 'Lab Technician'), ('Manufacturing Technician', 'Manufacturing Technician'), ('Analyst', 'Analyst'), ('QC Analyst', 'QC Analyst'), ('Manufacturing Analyst', 'Manufacturing Analyst'), ('Lead Analyst', 'Lead Analyst'), ('Lead QC Analyst', 'Lead QC Analyst'), ('Lead Mfg Analyst', 'Lead Mfg Analyst'), ('Supervisor', 'Supervisor'), ('QC Supervisor', 'QC Supervisor'), ('Mfg Supervisor', 'Mfg Supervisor'), ('Manager', 'Manager'), ('QC Manager', 'QC Manager'), ('Mfg Manager', 'Mfg Manager'), ('Director', 'Director'), ('QC Director', 'QC Director'), ('Mfg Director', 'Mfg Director')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='initiated',
            field=models.BooleanField(choices=[(True, 'Initiate'), (False, 'Do Not Initiate')], default=False),
        ),
        migrations.AlterField(
            model_name='sample',
            name='result_pf',
            field=models.BooleanField(blank=True, choices=[(True, 'Pass'), (False, 'Fail')], default=None, max_length=6, null=True),
        ),
    ]
