# Generated by Django 3.2.9 on 2021-12-09 21:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FreeLims', '0003_auto_20211209_0120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheminventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_date', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('name', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(max_length=100, verbose_name=(('Fisher Scientific', 'Fisher Scientific'), ('ThermoFisher Scientific', 'ThermoFisher Scientific'), ('Acros Organic', 'Acros Organic'), ('Sigma-Aldrich', 'Sigma-Aldrich'), ('Agilent', 'Agilent'), ('MilliporeSigma', 'MilliporeSigma'), ('Mettler Toledo', 'Mettler Toledo')))),
                ('manufacturer_lot', models.CharField(max_length=100)),
                ('expiry', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('Lab_lot', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('volume_size', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100, verbose_name=(('General Lab Storage', 'General Lab Storage (25°C)'), ('Refrigerator', 'Refrigerator (2-8°C)'), ('Freezer', 'Freezer')))),
                ('comments', models.CharField(max_length=250)),
                ('quarantine', models.BooleanField(default=False)),
                ('open_container', models.BooleanField(blank=True, default=None, null=True, verbose_name=((True, 'Open'), (False, 'Close')))),
                ('inv_disposal', models.BooleanField(blank=True, default=None, null=True, verbose_name=((True, 'Disposed'), (False, 'Active')))),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
