# Generated by Django 3.2.9 on 2021-12-12 18:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreeLims', '0004_cheminventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheminventory',
            name='inv_disposal',
            field=models.BooleanField(blank=True, choices=[(True, 'Disposed'), (False, 'Active')], default=False, null=True),
        ),
        migrations.AlterField(
            model_name='cheminventory',
            name='location',
            field=models.CharField(choices=[('General Lab Storage', 'General Lab Storage (25°C)'), ('Refrigerator', 'Refrigerator (2-8°C)'), ('Freezer', 'Freezer')], max_length=100),
        ),
        migrations.AlterField(
            model_name='cheminventory',
            name='manufacturer',
            field=models.CharField(choices=[('Fisher Scientific', 'Fisher Scientific'), ('ThermoFisher Scientific', 'ThermoFisher Scientific'), ('Acros Organic', 'Acros Organic'), ('Sigma-Aldrich', 'Sigma-Aldrich'), ('Agilent', 'Agilent'), ('MilliporeSigma', 'MilliporeSigma'), ('Mettler Toledo', 'Mettler Toledo')], max_length=100),
        ),
        migrations.AlterField(
            model_name='cheminventory',
            name='open_container',
            field=models.BooleanField(blank=True, choices=[(True, 'Open'), (False, 'Close')], default=True, null=True),
        ),
        migrations.AlterField(
            model_name='cheminventory',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
