# Generated by Django 3.2.9 on 2022-01-17 14:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FreeLims', '0004_profile_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheminventory',
            name='open_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='openUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cheminventory',
            name='open_date',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
