# Generated by Django 3.2.9 on 2022-02-02 19:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreeLims', '0005_auto_20220117_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(default=None, max_length=125, null=True)),
                ('user_count', models.IntegerField(default=None, null=True)),
                ('subscription_paid', models.BooleanField(default=False)),
                ('paid_until', models.DateTimeField(default=None)),
                ('payment_date', models.DateTimeField(default=None)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='Active_Status',
            field=models.BooleanField(blank=True, default=None, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
