# Generated by Django 3.2.9 on 2022-02-02 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreeLims', '0007_auto_20220202_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='paid_until',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='payment_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
